Disable Integration job on main branch
microsoft/react-native-macos pull request #947
Opened 2022-01-09 20:12 UTC by Saadnajmi

Our main branch isn't stable yet. I think this is because we've been doing our 0.66 merge  in the [fb66merge branch](https://github.com/HeyImChris/react-native-macos/tree/fb66merge) of @HeyImChris 's fork.

While main isn't stable,  let's disable another failing CI check to not unblock merges. We **should** track fixing this test (along with the disabled test in #945 ) because we will need nightly builds passing eventually.

2022-01-09 20:17 UTC, HeyImChris commented
Can we just fix this test instead of disabling it? The fix lives in 0.66 so should be doable to track it down.

2022-01-09 20:38 UTC, Saadnajmi commented
> Can we just fix this test instead of disabling it? The fix lives in 0.66 so should be doable to track it down.

Sorry, feel free to ignore me till tomorrow. 
We can, I just couldn't figure it yet. I assumed the test would start passing again whenever we merged the 0.66 merge branch.

2022-01-10 18:30 UTC, HeyImChris requested changes

2022-01-10 18:30 UTC, HeyImChris commented on .ado/apple-integration.yml
> +    # - main
If we do disable a test, we should have a bug tracking adding it back so it's not lost in the ether

2022-01-13 18:55 UTC, HeyImChris commented
> > Can we just fix this test instead of disabling it? The fix lives in 0.66 so should be doable to track it down.
> 
> Sorry, feel free to ignore me till tomorrow. We can, I just couldn't figure it yet. I assumed the test would start passing again whenever we merged the 0.66 merge branch.

Yep test passes on 0.66! We'd just need a follow up to re-enable this test once 0.66 goes in which I'm hoping will be today.

2022-01-14 23:43 UTC, HeyImChris approved these changes

2022-01-14 23:43 UTC, merged